optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 5e-4
scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.2
  patience: 5
model:
  backbone_name: efficientnet-b2
  metric: arc_margin
  num_classes: 18463
  pretrain: True
  backbone_output: 1408

loss: focal_loss
train:
  print_freq: 10 # print info every N batch
  dataset:
    input_file: ./input_file/train_data_combined_tiki_and_shopee_18463_27_6_22.parquet
    root_dir: {
      shopee: "/home/longle/shopee-product-matching/train_images/",
      tiki: "/home/longle/images/images/"
    }
    image_key: normalized_url_image
    label_key: train_label_new
    data_source_key: data_source
  num_workers: 4
  batch_size: 24
  shuffle: True
  epochs: 300
  data_augmentation:
    output_shape: 380
  save_interval: 1
evaluate:
  batch_size: 8
  dataset:
    input_file: ./input_file/val_set_pair.parquet
    root_dir: /home/longle/images/images/
    first_image_key: first_image_file_name
    second_image_key: second_image_file_name
    pair_key: pair_result
  num_workers: 4
  shuffle: False
display: True
checkpoints_path: checkpoints